# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MG_HomeSecurity_HMI_QT.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TCam = QtWidgets.QTabWidget(self.centralwidget)
        self.TCam.setGeometry(QtCore.QRect(10, 110, 381, 271))
        self.TCam.setObjectName("TCam")
        self.Cam1 = QtWidgets.QWidget()
        self.Cam1.setObjectName("Cam1")
        self.CBCam1Enable = QtWidgets.QCheckBox(self.Cam1)
        self.CBCam1Enable.setGeometry(QtCore.QRect(10, 10, 91, 20))
        self.CBCam1Enable.setChecked(True)
        self.CBCam1Enable.setObjectName("CBCam1Enable")
        self.TabSettingCam1 = QtWidgets.QTabWidget(self.Cam1)
        self.TabSettingCam1.setGeometry(QtCore.QRect(0, 40, 381, 211))
        self.TabSettingCam1.setObjectName("TabSettingCam1")
        self.F1 = QtWidgets.QWidget()
        self.F1.setObjectName("F1")
        self.tabWidget = QtWidgets.QTabWidget(self.F1)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 371, 181))
        self.tabWidget.setObjectName("tabWidget")
        self.Z1 = QtWidgets.QWidget()
        self.Z1.setObjectName("Z1")
        self.label_2 = QtWidgets.QLabel(self.Z1)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 47, 20))
        self.label_2.setObjectName("label_2")
        self.LEC1SettingF1Z1P1 = QtWidgets.QLineEdit(self.Z1)
        self.LEC1SettingF1Z1P1.setGeometry(QtCore.QRect(70, 30, 91, 20))
        self.LEC1SettingF1Z1P1.setObjectName("LEC1SettingF1Z1P1")
        self.LEC1SettingF1Z1P2 = QtWidgets.QLineEdit(self.Z1)
        self.LEC1SettingF1Z1P2.setGeometry(QtCore.QRect(70, 50, 91, 20))
        self.LEC1SettingF1Z1P2.setObjectName("LEC1SettingF1Z1P2")
        self.LEC1SettingF1Z1P3 = QtWidgets.QLineEdit(self.Z1)
        self.LEC1SettingF1Z1P3.setGeometry(QtCore.QRect(70, 70, 91, 20))
        self.LEC1SettingF1Z1P3.setObjectName("LEC1SettingF1Z1P3")
        self.label_4 = QtWidgets.QLabel(self.Z1)
        self.label_4.setGeometry(QtCore.QRect(20, 70, 47, 20))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.Z1)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 47, 20))
        self.label_3.setObjectName("label_3")
        self.LEC1EventF1Z1P1 = QtWidgets.QLineEdit(self.Z1)
        self.LEC1EventF1Z1P1.setEnabled(False)
        self.LEC1EventF1Z1P1.setGeometry(QtCore.QRect(260, 30, 91, 20))
        self.LEC1EventF1Z1P1.setObjectName("LEC1EventF1Z1P1")
        self.label_5 = QtWidgets.QLabel(self.Z1)
        self.label_5.setGeometry(QtCore.QRect(166, 30, 91, 20))
        self.label_5.setObjectName("label_5")
        self.LEC1EventF1Z1P2 = QtWidgets.QLineEdit(self.Z1)
        self.LEC1EventF1Z1P2.setEnabled(False)
        self.LEC1EventF1Z1P2.setGeometry(QtCore.QRect(260, 50, 91, 20))
        self.LEC1EventF1Z1P2.setObjectName("LEC1EventF1Z1P2")
        self.label_6 = QtWidgets.QLabel(self.Z1)
        self.label_6.setGeometry(QtCore.QRect(166, 70, 91, 20))
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.Z1)
        self.label_8.setGeometry(QtCore.QRect(166, 50, 91, 20))
        self.label_8.setObjectName("label_8")
        self.LEC1EventF1Z1P3 = QtWidgets.QLineEdit(self.Z1)
        self.LEC1EventF1Z1P3.setEnabled(False)
        self.LEC1EventF1Z1P3.setGeometry(QtCore.QRect(260, 70, 91, 20))
        self.LEC1EventF1Z1P3.setObjectName("LEC1EventF1Z1P3")
        self.label_9 = QtWidgets.QLabel(self.Z1)
        self.label_9.setGeometry(QtCore.QRect(90, 10, 47, 20))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.Z1)
        self.label_10.setGeometry(QtCore.QRect(280, 10, 47, 20))
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.Z1, "")
        self.Z2 = QtWidgets.QWidget()
        self.Z2.setObjectName("Z2")
        self.tabWidget.addTab(self.Z2, "")
        self.TabSettingCam1.addTab(self.F1, "")
        self.F2 = QtWidgets.QWidget()
        self.F2.setObjectName("F2")
        self.TabSettingCam1.addTab(self.F2, "")
        self.TCam.addTab(self.Cam1, "")
        self.Cam2 = QtWidgets.QWidget()
        self.Cam2.setObjectName("Cam2")
        self.CBCam2Enable = QtWidgets.QCheckBox(self.Cam2)
        self.CBCam2Enable.setGeometry(QtCore.QRect(10, 10, 91, 20))
        self.CBCam2Enable.setChecked(True)
        self.CBCam2Enable.setObjectName("CBCam2Enable")
        self.TCam.addTab(self.Cam2, "")
        self.Cam3 = QtWidgets.QWidget()
        self.Cam3.setObjectName("Cam3")
        self.TCam.addTab(self.Cam3, "")
        self.Cam4 = QtWidgets.QWidget()
        self.Cam4.setObjectName("Cam4")
        self.TCam.addTab(self.Cam4, "")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 80, 231, 21))
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 0, 231, 21))
        self.label_7.setObjectName("label_7")
        self.CBArmement = QtWidgets.QCheckBox(self.centralwidget)
        self.CBArmement.setGeometry(QtCore.QRect(20, 30, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.CBArmement.setFont(font)
        self.CBArmement.setIconSize(QtCore.QSize(16, 16))
        self.CBArmement.setObjectName("CBArmement")
        self.PBAcquittement = QtWidgets.QPushButton(self.centralwidget)
        self.PBAcquittement.setGeometry(QtCore.QRect(330, 20, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PBAcquittement.setFont(font)
        self.PBAcquittement.setObjectName("PBAcquittement")
        self.RBPreAlarmeActive = QtWidgets.QRadioButton(self.centralwidget)
        self.RBPreAlarmeActive.setGeometry(QtCore.QRect(150, 20, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.RBPreAlarmeActive.setFont(font)
        self.RBPreAlarmeActive.setObjectName("RBPreAlarmeActive")
        self.RBPAlarmeActive = QtWidgets.QRadioButton(self.centralwidget)
        self.RBPAlarmeActive.setGeometry(QtCore.QRect(150, 40, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.RBPAlarmeActive.setFont(font)
        self.RBPAlarmeActive.setObjectName("RBPAlarmeActive")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 29))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.MMQuitter = QtWidgets.QAction(MainWindow)
        self.MMQuitter.setObjectName("MMQuitter")
        self.menuMenu.addAction(self.MMQuitter)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.TCam.setCurrentIndex(0)
        self.TabSettingCam1.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CBCam1Enable.setText(_translate("MainWindow", "Enable"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">P1 - Seuil</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">P3 - Box</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">P2 - Filtre</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">P1 - ObjectName</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">P3 - Box</p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">P2 - Score</p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Settings</p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Events</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Z1), _translate("MainWindow", "Z1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Z2), _translate("MainWindow", "Z2"))
        self.TabSettingCam1.setTabText(self.TabSettingCam1.indexOf(self.F1), _translate("MainWindow", "F1"))
        self.TabSettingCam1.setTabText(self.TabSettingCam1.indexOf(self.F2), _translate("MainWindow", "F2"))
        self.TCam.setTabText(self.TCam.indexOf(self.Cam1), _translate("MainWindow", "Cam1"))
        self.CBCam2Enable.setText(_translate("MainWindow", "Enable"))
        self.TCam.setTabText(self.TCam.indexOf(self.Cam2), _translate("MainWindow", "Cam2"))
        self.TCam.setTabText(self.TCam.indexOf(self.Cam3), _translate("MainWindow", "Cam3"))
        self.TCam.setTabText(self.TCam.indexOf(self.Cam4), _translate("MainWindow", "Cam4"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Configuration des caméras</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Gestion alarme</span></p></body></html>"))
        self.CBArmement.setText(_translate("MainWindow", "Armement"))
        self.PBAcquittement.setText(_translate("MainWindow", "Acquittement"))
        self.RBPreAlarmeActive.setText(_translate("MainWindow", "Pré alarme active"))
        self.RBPAlarmeActive.setText(_translate("MainWindow", "Alarme active"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.MMQuitter.setText(_translate("MainWindow", "Quitter"))
